[package]
name = "timmie"
version = "0.1.0"
edition = "2021"

[dependencies]
poise = "0.4.0"
tokio = { version = "1.21.2", features = ["rt-multi-thread"] }
dotenv = "0.15.0"
serde = "1.0.145"
serde_json = "1.0.86"
rust-embed = "6.4.1"
