[package]
name = "ushi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.12"
http-cache = "0.7.0"
serde = "1.0.147"
strum = { version = "0.24.1", features = ["derive"] }
